.\" groff -man -Tascii lispkit.1 | less
.TH lispkit 1 
.SH "NAME"
Lispkit \- a functional programming language similar to Lisp
.SH "SYNOPSIS"
.B lispkit 
.I function-file
[
.I arguments-file
]
.SH "OPTIONS"
.IP function-file
A file containing lispkit machine code.
.IP argument-file 
A file containing lispkit arguments. 
If not present, arguments can be entered through stdin.
.SH "FILES"
.IP compiler
Lispkit compiler in machine code form
.IP compiler
Lispkit compiler in source code form
.SH "ENVIRONMENT"
.B LISPKIT_MEMORY
.SH "AUTHOR"
This program is based on the Lispkit described in
"Functional Programming Application and Implementation", 
by Peter Henderson (ISBN 0-13-331579-7).
This Lispkit and man page by A. Carl Douglas (carl.douglas@gmail.com).

